import { createContext, useContext, useState } from 'react'

const translations = {
  az: {
    nav: {
      links: [
        { label: 'Haqqımızda', to: '/haqqimizda' },
        { label: 'İşlərimiz', to: '/islerimiz' },
        { label: 'Xidmətlər', to: '/xidmetler' },
        { label: 'Əlaqə', to: '/elaqe' },
      ],
      cta: 'Təklif Al',
    },
    hero: {
      label: 'Kreativ Agentlik — Bakı, Azərbaycan',
      headline: 'Biz Vizyonunuzu Reallığa Çeviririk',
      words: ['Vizyonu', 'İdeyaları', 'Brendinizi', 'Gələcəyi'],
      wordsSuffix: 'reallığa çeviririk',
      subtext: 'Brendinizi güclü vizual dil, strateji düşüncə və kreativ həllərlə irəliyə aparırıq.',
      ctaPrimary: 'İşlərimizə Bax',
      ctaSecondary: 'Əlaqə',
    },
    homeAbout: {
      label: 'Haqqımızda',
      heading1: 'İnsan',
      heading2: 'və Vizyon',
      body: 'Best Vision Agentliyi olaraq biz hər müştərinin brendini ilk görüşdən əhəmiyyətli bir təəssürat yaradan bir kimliyə çeviririk.',
      bodyStrong: 'İlk təəssürat',
      bodyEnd: 'biznesin taleyini həll edir.',
      stats: [['100%', 'Kreativ Yanaşma'], ['7/24', 'Texniki Dəstək'], ['∞', 'Sonsuz Vizyon']],
      quotePre: 'Müştəriləriniz brendinizi',
      quoteAccent: '0.05 saniyə',
      quotePost: 'ərzində qiymətləndirir.',
      quoteAttrib: '— Best Vision Fəlsəfəsi',
      cta: 'Ətraflı Məlumat →',
    },
    homeServices: {
      label: 'Xidmətlər',
      heading1: 'Həll',
      heading2: 'Mərkəzi',
      cta: 'Bütün Xidmətlər →',
    },
    homePortfolio: {
      label: 'Portfolio',
      heading1: 'Seçilmiş',
      heading2: 'İşlər',
      cta: 'Bütün İşlər →',
      hoverCta: 'Ətraflı Bax',
      projects: [
        { title: 'LuxBrand Azərbaycan', category: 'Brend Kimliyi', result: '+40% satış' },
        { title: 'TechStart Kampaniyası', category: 'Rəqəmsal Reklam', result: '1200+ istifadəçi' },
        { title: 'RealEstate Portal', category: 'Veb Tərtibat', result: '+300% trafik' },
      ],
    },
    homeCta: {
      label: 'Başlayaq',
      heading1: 'Layihənizi',
      heading2: 'bu gün başlayın',
      body: '24 saat ərzində sizinlə əlaqə saxlayacağıq. İlk konsultasiya pulsuzdur.',
      cta: 'Əlaqə →',
    },
    about: {
      label: 'Haqqımızda',
      heading1: 'İnsan',
      heading2: 'və Vizyon',
      body1: 'Best Vision Agentliyi olaraq biz hər müştərinin brendini ilk görüşdən əhəmiyyətli bir təəssürat yaradan bir kimliyə çeviririk. Çünki biliririk ki,',
      bodyStrong: 'ilk təəssürat',
      body2: 'biznesin taleyini həll edir.',
      body3: 'Hər layihəmizdə vizual qüdrət, strateji dərinlik və emosional rezonans birləşir.',
      stats: [['100%', 'Kreativ Yanaşma'], ['7/24', 'Texniki Dəstək'], ['∞', 'Sonsuz Vizyon']],
      quoteLabel: 'İlk Təəssüratın Gücü',
      quotePre: 'Müştəriləriniz brendinizi',
      quoteAccent: '0.05 saniyə',
      quoteMid: 'ərzində qiymətləndirir. Biz bu saniyəni sizin lehinizə işlədiririk.',
      quoteAttrib: '— Best Vision Fəlsəfəsi',
      timelineLabel: 'İnkişaf Yolumuz',
      timeline: [
        { year: 'Oktyabr 2025', title: 'Yaranış', desc: 'Best Vision agentliyi kiçik bir komanda ilə böyük bir vizyonla quruldu.' },
        { year: 'Aprel 2026', title: 'Best Vision Web', desc: 'Rəqəmsal ekosistemimizi genişləndirərək veb xidmətləri qolumuzu yaratdıq.' },
        { year: 'May 2026', title: 'İlk Mərkəz', desc: 'Komandamızın böyüməsi ilə birlikdə rəsmi ofisimiz fəaliyyətə başladı.' },
      ],
    },
    services: {
      label: 'Xidmətlər',
      heading1: 'Həll',
      heading2: 'Mərkəzi',
      subtext: 'Brendinizin ehtiyac duyduğu hər həll bir dam altında. Strateji düşüncə, kreativ icra və texniki mükəmməllik.',
      bottomText: 'Xüsusi tələbləriniz var mı? Fərdi paket üçün bizimlə əlaqə saxlayın.',
      bottomCta: 'Fərdi Paket Tələb Et',
      collapsed: 'Ətraflı',
      expanded: 'Bağla',
      cards: [
        { title: 'Digital Growth', subtitle: 'Rəqəmsal Böyümə', desc: 'SMM və rəqəmsal reklam strategiyaları.', detail: 'Hədəflənmiş sosial media strategiyaları, ödənişli reklam kampaniyaları (Meta, Google, TikTok), analitika və ROI optimallaşdırması ilə brendinizi rəqəmsal dünyada lider mövqeyə daşıyırıq.', features: ['Instagram & Facebook Ads', 'Google Ads & SEO', 'TikTok Kampaniyaları', 'Analitika & Hesabatlar'] },
        { title: 'Visual Identity', subtitle: 'Vizual Kimlik', desc: 'Brendinq, loqo və korporativ kimlik dizaynı.', detail: 'Brendinizin ruhunu vizual bir dilə çeviririk. Loqo, rəng palitrasından tutmuş tam korporativ kimlik paketinə qədər hər detalı sizin brendinizin hekayəsini danışır.', features: ['Loqo & Brendinq', 'Korporativ Kimlik Paketi', 'Qablaşdırma Dizaynı', 'Brend Qaydaları'] },
        { title: 'Web Architecture', subtitle: 'Veb Memarlığı', desc: 'Saytların hazırlanması və texniki optimizasiya.', detail: 'Estetik görünüş ilə yüksək performansın kəsişdiyi nöqtədə saytlar qururuq. UI/UX dizayndan backend infrastrukturuna, SEO optimallaşdırmasından sürət optimizasiyasına qədər.', features: ['UI/UX Dizayn', 'Frontend & Backend', 'E-Commerce Həlləri', 'Texniki SEO'] },
        { title: 'Creative Content', subtitle: 'Kreativ Kontent', desc: 'Foto/video çəkilişlər və kreativ prodakşn.', detail: 'Professional foto/video çəkilişlərdən motion graphics-ə, korporativ filmlərə qədər brendinizin hekayəsini vizual olaraq danışırıq.', features: ['Professional Fotosessiya', 'Video Prodakşn', 'Motion Graphics', 'Kontent Strategiyası'] },
      ],
    },
    portfolio: {
      label: 'Portfolio',
      heading1: 'Eksklüziv',
      heading2: 'İşlərimiz',
      subtext: 'Hər layihə bir hekayədir. Biz həmin hekayəni ən güclü vizual dillə danışırıq.',
      clickHint: '— Klik et, ətraflı bax',
      modalGoal: 'Məqsəd',
      modalStrategy: 'Strategiya',
      modalResult: 'Nəticə',
      projects: [
        { title: 'LuxBrand Azərbaycan', category: 'Brend Kimliyi', goal: 'Yerli lüks brendin vizual kimliyini yenidən qurmaq', strategy: 'Minimalst dizayn dili, premium rəng palitrasının müəyyən edilməsi və tam korporativ kimliy paketi', result: 'Satışlarda 40% artım', resultDetail: 'İlk 3 ayda onlayn satışlar 40% artdı, brendin tanınırlığı 2.5x artdı.' },
        { title: 'TechStart Kampaniyası', category: 'Rəqəmsal Reklam', goal: 'Startapın ilk müştəri bazasını qurmaq', strategy: 'Hədəflənmiş sosial media reklamları, influencer əməkdaşlıqları', result: '1200+ yeni istifadəçi', resultDetail: '2 aylıq kampaniyada 1200+ aktiv istifadəçi, CAC 60% azaldı.' },
        { title: 'GreenLife SMM', category: 'Sosial Media', goal: 'Ekoloji brendin onlayn varlığını gücləndirmək', strategy: 'Məzmun strategiyası, reels prodaksiyonu, icma qurma', result: '85K izləyici artımı', resultDetail: 'Instagram hesabı 3 ayda 12K-dan 97K izləyiciyə çatdı.' },
        { title: 'RealEstate Portal', category: 'Veb Tərtibat', goal: 'Müasir daşınmaz əmlak platforması yaratmaq', strategy: 'UX araşdırması, sürətli performans optimizasiyası, mobil-first dizayn', result: '+300% trafik artımı', resultDetail: 'Yeni sayt 3 ayda 300% daha çox trafik, dönüşüm 2x artdı.' },
        { title: 'FoodChain Branding', category: 'Vizual Kimlik', goal: 'Restoran zəncirinin brendini vahid bir dildə birləşdirmək', strategy: 'Brend qaydaları sənədi, qablaşdırma dizaynı, menyular', result: '25% müştəri saxlama artımı', resultDetail: 'Yeni kimliklə müştəri geri dönüşü 25% yüksəldi.' },
        { title: 'Fashion Week AZ', category: 'Foto/Video', goal: 'Azərbaycan moda həftəsinin kreativ kontent istehsalı', strategy: '2 günlük foto/video çəkiliş, post-prodaksiya, rəqəmsal yayım', result: '2M+ görüntüləmə', resultDetail: 'Yayım materialları sosial mediada 2 milyon görüntüləmə topladı.' },
      ],
    },
    partners: {
      label: 'Partnyorlar',
      heading1: 'Güvən',
      heading2: 'Simvolları',
      subtext: 'Azərbaycanın aparıcı brendləri Best Vision-a güvənir. Biz nəticə çatdırırıq.',
      comingSoon: 'Yaxın zamanlarda...',
      stats: [
        ['50+', 'Aktiv Müştəri', 'Azərbaycan üzrə'],
        ['200+', 'Tamamlanmış Layihə', '2018-dən indiyə'],
        ['98%', 'Müştəri Məmnuniyyəti', 'Sorğular əsasında'],
        ['6+', 'İl Sektoreda', 'Davamlı uğur'],
      ],
    },
    contact: {
      label: 'Əlaqə',
      heading1: 'Təklif Al',
      heading2: 'Bu Gün',
      subtext: 'Layihənizi paylaşın, biz sizin üçün ən optimal həlli müəyyənləşdirək. Cavabı 24 saat ərzində veririk.',
      infoItems: [
        { label: 'E-poçt', value: 'bestvisionagency1@gmail.com', icon: '✉' },
        { label: 'Telefon', value: '+994 50 397 03 01', icon: '☎' },
        { label: 'Ünvan', value: 'Əlövsət Quliyev küç., 92, Bakı', icon: '◎', href: 'https://www.google.com/maps/search/?api=1&query=Əlövsət+Quliyev+küçəsi+92+Baku' },
      ],
      steps: [{ number: '01', title: 'Xidmət' }, { number: '02', title: 'Büdcə' }, { number: '03', title: 'Əlaqə' }],
      step0Title: 'Hansı xidmət lazımdır?',
      step1Title: 'Büdcə aralığınız?',
      step2Title: 'Əlaqə məlumatı',
      services: ['Digital Growth (SMM & Reklam)', 'Visual Identity (Brend & Loqo)', 'Web Architecture (Sayt)', 'Creative Content (Foto/Video)', 'Kompleks Paket'],
      budgets: ['Müzakirə edilsin', '500 - 1,000 AZN', '1,000 - 3,000 AZN', '3,000 - 7,000 AZN', '7,000+ AZN'],
      fields: [
        { name: 'name', label: 'Ad Soyad', type: 'text', required: true },
        { name: 'email', label: 'E-poçt', type: 'email', required: true },
        { name: 'phone', label: 'Telefon', type: 'tel', required: true },
      ],
      messageLabel: 'Mesajınız',
      messagePlaceholder: 'Layihəniz haqqında qısaca yazın...',
      submit: 'Göndər',
      back: '← Geri',
      serviceLabel: 'Xidmət',
      budgetLabel: 'Büdcə',
      successTitle: 'Göndərildi!',
      successText: 'Müraciətiniz qəbul edildi. 24 saat ərzində sizinlə əlaqə saxlayacağıq.',
      errorRequired: 'Bu sahə mütləqdir.',
      errorEmail: 'Düzgün e-poçt ünvanı daxil edin.',
      errorPhone: 'Düzgün telefon nömrəsi daxil edin.',
    },
    footer: {
      tagline: 'Brendinizi reallığa çeviririk. Kreativ agentlik olaraq hər layihədə mükəmməlliyi hədəfləyirik.',
      navLabel: 'Naviqasiya',
      contactLabel: 'Əlaqə',
      contactItems: [['bestvisionagency1@gmail.com', 'E-poçt'], ['+994 50 397 03 01', 'Telefon'], ['Əlövsət Quliyev küç., 92, Bakı', 'Ünvan', 'https://www.google.com/maps/search/?api=1&query=Əlövsət+Quliyev+küçəsi+92+Baku']],
      copyright: '© 2026 Best Vision Agency. Bütün hüquqlar qorunur.',
      legal: [],
    },
    floating: {
      label: 'Bizimlə əlaqə saxlayın:',
      cta: 'Təklif Al',
    },
  },

  en: {
    nav: {
      links: [
        { label: 'About Us', to: '/haqqimizda' },
        { label: 'Our Work', to: '/islerimiz' },
        { label: 'Services', to: '/xidmetler' },
        { label: 'Contact', to: '/elaqe' },
      ],
      cta: 'Get a Quote',
    },
    hero: {
      label: 'Creative Agency — Baku, Azerbaijan',
      headline: 'We turn your vision into reality',
      words: ['Vision', 'Ideas', 'Brand', 'Future'],
      wordsSuffix: 'into reality',
      subtext: 'We elevate your brand with powerful visual language, strategic thinking, and creative solutions.',
      ctaPrimary: 'View Our Work',
      ctaSecondary: 'Contact',
    },
    homeAbout: {
      label: 'About Us',
      heading1: 'People',
      heading2: '& Vision',
      body: 'At Best Vision Agency, we transform every client\'s brand into an identity that creates a powerful first impression.',
      bodyStrong: 'First impressions',
      bodyEnd: 'determine the fate of a business.',
      stats: [['100%', 'Creative Approach'], ['24/7', 'Technical Support'], ['∞', 'Endless Vision']],
      quotePre: 'Your customers evaluate your brand in just',
      quoteAccent: '0.05 seconds',
      quotePost: '.',
      quoteAttrib: '— Best Vision Philosophy',
      cta: 'Learn More →',
    },
    homeServices: {
      label: 'Services',
      heading1: 'Solutions',
      heading2: 'Hub',
      cta: 'All Services →',
    },
    homePortfolio: {
      label: 'Portfolio',
      heading1: 'Selected',
      heading2: 'Work',
      cta: 'All Projects →',
      hoverCta: 'View Details',
      projects: [
        { title: 'LuxBrand Azerbaijan', category: 'Brand Identity', result: '+40% sales' },
        { title: 'TechStart Campaign', category: 'Digital Advertising', result: '1,200+ users' },
        { title: 'RealEstate Portal', category: 'Web Development', result: '+300% traffic' },
      ],
    },
    homeCta: {
      label: "Let's Begin",
      heading1: 'Start your project',
      heading2: 'today',
      body: "We'll reach out within 24 hours. The first consultation is completely free.",
      cta: 'Contact →',
    },
    about: {
      label: 'About Us',
      heading1: 'People',
      heading2: '& Vision',
      body1: 'At Best Vision Agency, we transform every client\'s brand into an identity that creates a powerful first impression from the very first encounter. Because we know that',
      bodyStrong: 'first impressions',
      body2: 'determine the fate of a business.',
      body3: 'Every project unites visual power, strategic depth, and emotional resonance.',
      stats: [['100%', 'Creative Approach'], ['24/7', 'Technical Support'], ['∞', 'Endless Vision']],
      quoteLabel: 'The Power of First Impressions',
      quotePre: 'Your customers evaluate your brand in just',
      quoteAccent: '0.05 seconds',
      quoteMid: '. We make that moment work in your favor.',
      quoteAttrib: '— Best Vision Philosophy',
      timelineLabel: 'Our Journey',
      timeline: [
        { year: 'October 2025', title: 'Creation', desc: 'Best Vision agency was founded by a small team with a big vision.' },
        { year: 'April 2026', title: 'Best Vision Web', desc: 'We expanded our digital ecosystem by launching our web services branch.' },
        { year: 'May 2026', title: 'First Office', desc: 'With the growth of our team, our official office started its operations.' },
      ],
    },
    services: {
      label: 'Services',
      heading1: 'Solutions',
      heading2: 'Hub',
      subtext: 'Every solution your brand needs, under one roof. Strategic thinking, creative execution, and technical excellence.',
      bottomText: 'Have specific requirements? Contact us for a custom package.',
      bottomCta: 'Request a Custom Package',
      collapsed: 'Details',
      expanded: 'Close',
      cards: [
        { title: 'Digital Growth', subtitle: 'Digital Growth', desc: 'SMM and digital advertising strategies.', detail: 'We elevate your brand to a leading position in the digital world through targeted social media strategies, paid ad campaigns (Meta, Google, TikTok), analytics, and ROI optimization.', features: ['Instagram & Facebook Ads', 'Google Ads & SEO', 'TikTok Campaigns', 'Analytics & Reports'] },
        { title: 'Visual Identity', subtitle: 'Visual Identity', desc: 'Branding, logo, and corporate identity design.', detail: "We translate the essence of your brand into a visual language. From logo and color palette to a complete corporate identity package — every detail tells your brand's story.", features: ['Logo & Branding', 'Corporate Identity Kit', 'Packaging Design', 'Brand Guidelines'] },
        { title: 'Web Architecture', subtitle: 'Web Architecture', desc: 'Website development and technical optimization.', detail: 'We build websites at the intersection of aesthetic beauty and high performance — from UI/UX design and backend infrastructure to SEO and speed optimization.', features: ['UI/UX Design', 'Frontend & Backend', 'E-Commerce Solutions', 'Technical SEO'] },
        { title: 'Creative Content', subtitle: 'Creative Content', desc: 'Photo/video shoots and creative production.', detail: "From professional photo and video shoots to motion graphics and corporate films, we tell your brand's story visually.", features: ['Professional Photo Shoots', 'Video Production', 'Motion Graphics', 'Content Strategy'] },
      ],
    },
    portfolio: {
      label: 'Portfolio',
      heading1: 'Exclusive',
      heading2: 'Work',
      subtext: 'Every project is a story. We tell that story in the most powerful visual language.',
      clickHint: '— Click to explore',
      modalGoal: 'Objective',
      modalStrategy: 'Strategy',
      modalResult: 'Result',
      projects: [
        { title: 'LuxBrand Azerbaijan', category: 'Brand Identity', goal: 'Rebuild the visual identity of a local luxury brand', strategy: 'Minimalist design language, definition of a premium color palette, and complete corporate identity package', result: '40% sales increase', resultDetail: 'Online sales grew by 40% in the first 3 months; brand recognition increased 2.5x.' },
        { title: 'TechStart Campaign', category: 'Digital Advertising', goal: "Build the startup's first customer base", strategy: 'Targeted social media ads, influencer partnerships', result: '1,200+ new users', resultDetail: '1,200+ active users acquired in a 2-month campaign; CAC reduced by 60%.' },
        { title: 'GreenLife SMM', category: 'Social Media', goal: "Strengthen an eco-brand's online presence", strategy: 'Content strategy, reels production, community building', result: '85K follower growth', resultDetail: 'Instagram account grew from 12K to 97K followers in 3 months.' },
        { title: 'RealEstate Portal', category: 'Web Development', goal: 'Create a modern real estate platform', strategy: 'UX research, performance optimization, mobile-first design', result: '+300% traffic growth', resultDetail: 'New site drove 300% more traffic in 3 months; conversions doubled.' },
        { title: 'FoodChain Branding', category: 'Visual Identity', goal: "Unify a restaurant chain's brand under one visual language", strategy: 'Brand guidelines document, packaging design, menus', result: '25% customer retention boost', resultDetail: 'Customer return rate rose 25% with the new identity.' },
        { title: 'Fashion Week AZ', category: 'Photo / Video', goal: "Creative content production for Azerbaijan's fashion week", strategy: '2-day photo/video shoot, post-production, digital distribution', result: '2M+ views', resultDetail: 'Distribution materials reached 2 million views on social media.' },
      ],
    },
    partners: {
      label: 'Partners',
      heading1: 'Trusted',
      heading2: 'By The Best',
      subtext: "Azerbaijan's leading brands trust Best Vision. We deliver results.",
      comingSoon: 'Coming soon...',
      stats: [
        ['50+', 'Active Clients', 'Across Azerbaijan'],
        ['200+', 'Completed Projects', 'Since 2018'],
        ['98%', 'Client Satisfaction', 'Survey-based'],
        ['6+', 'Years in Industry', 'Consistent success'],
      ],
    },
    contact: {
      label: 'Contact',
      heading1: 'Get a Quote',
      heading2: 'Today',
      subtext: 'Share your project and we will find the optimal solution for you. We respond within 24 hours.',
      infoItems: [
        { label: 'Email', value: 'bestvisionagency1@gmail.com', icon: '✉' },
        { label: 'Phone', value: '+994 50 397 03 01', icon: '☎' },
        { label: 'Address', value: '92 Alovsat Guliyev St., Baku', icon: '◎', href: 'https://www.google.com/maps/search/?api=1&query=Əlövsət+Quliyev+küçəsi+92+Baku' },
      ],
      steps: [{ number: '01', title: 'Service' }, { number: '02', title: 'Budget' }, { number: '03', title: 'Contact' }],
      step0Title: 'Which service do you need?',
      step1Title: 'What is your budget range?',
      step2Title: 'Your contact details',
      services: ['Digital Growth (SMM & Ads)', 'Visual Identity (Brand & Logo)', 'Web Architecture (Website)', 'Creative Content (Photo/Video)', 'Full Package'],
      budgets: ['To be discussed', '500 - 1,000 AZN', '1,000 - 3,000 AZN', '3,000 - 7,000 AZN', '7,000+ AZN'],
      fields: [
        { name: 'name', label: 'Full Name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email', required: true },
        { name: 'phone', label: 'Phone', type: 'tel', required: false },
      ],
      messageLabel: 'Your Message',
      messagePlaceholder: 'Briefly describe your project...',
      submit: 'Send',
      back: '← Back',
      serviceLabel: 'Service',
      budgetLabel: 'Budget',
      successTitle: 'Sent!',
      successText: 'Your inquiry has been received. We will contact you within 24 hours.',
    },
    footer: {
      tagline: 'We turn your brand into reality. As a creative agency, we pursue excellence in every project.',
      navLabel: 'Navigation',
      contactLabel: 'Contact',
      contactItems: [['bestvisionagency1@gmail.com', 'Email'], ['+994 50 397 03 01', 'Phone'], ['92 Alovsat Guliyev St., Baku', 'Address', 'https://www.google.com/maps/search/?api=1&query=Əlövsət+Quliyev+küçəsi+92+Baku']],
      copyright: '© 2026 Best Vision Agency. All rights reserved.',
      legal: [],
    },
    floating: {
      label: 'Contact us:',
      cta: 'Get a Quote',
    },
  },
}

const LanguageContext = createContext({ lang: 'az', t: translations.az, toggleLang: () => {} })

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('bv-lang') || 'az' } catch { return 'az' }
  })

  const toggleLang = () => {
    const next = lang === 'az' ? 'en' : 'az'
    setLang(next)
    try { localStorage.setItem('bv-lang', next) } catch {}
  }

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
